annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: ngrok Ingress Controller
  catalog.cattle.io/release-name: kubernetes-ingress-controller
apiVersion: v2
appVersion: 0.12.1
dependencies:
- name: common
  repository: file://./charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: A Kubernetes ingress controller built using ngrok.
home: https://ngrok.com
icon: file://assets/icons/kubernetes-ingress-controller.svg
keywords:
- ngrok
- networking
- ingress
- edge
- api gateway
name: kubernetes-ingress-controller
sources:
- https://github.com/ngrok/kubernetes-ingress-controller
version: 0.14.1
