annotations:
  artifacthub.io/changes: |
    - kind: security
      description: "fixed critical vulnerabilities in compose upgraded to v2.28.1-1.5.0"
    - kind: security
      description: "fixed critical vulnerabilities in pikolo upgraded to 0.14.1"
    - kind: security
      description: "fixed critical vulnerabilities in docker-tag-pusher upgraded to 1.3.14"
  artifacthub.io/containsSecurityUpdates: "false"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Codefresh
  catalog.cattle.io/kube-version: '>=1.18-0'
  catalog.cattle.io/release-name: cf-runtime
apiVersion: v2
dependencies:
- name: cf-common
  repository: file://./charts/cf-common
  version: 0.16.0
description: A Helm chart for Codefresh Runner
home: https://codefresh.io/
icon: file://assets/icons/cf-runtime.png
keywords:
- codefresh
- runner
kubeVersion: '>=1.18-0'
maintainers:
- name: codefresh
  url: https://codefresh-io.github.io/
name: cf-runtime
sources:
- https://github.com/codefresh-io/venona
version: 6.3.50
