annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Harbor
  catalog.cattle.io/kube-version: '>=1.20-0'
  catalog.cattle.io/release-name: harbor
apiVersion: v1
appVersion: 2.11.1
description: An open source trusted cloud native registry that stores, signs, and
  scans content
home: https://goharbor.io
icon: file://assets/icons/harbor.png
keywords:
- docker
- registry
- harbor
kubeVersion: '>=1.20-0'
maintainers:
- email: yan-yw.wang@broadcom.com
  name: Yan Wang
- email: wenkai.yin@broadcom.com
  name: Wenkai Yin
- email: miner.yang@broadcom.com
  name: Miner Yang
- email: shengwen.yu@broadcom.com
  name: Shengwen Yu
name: harbor
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
version: 1.15.1
